### ISSUE TITLE
Failed update, broken system, needed rolling back.

### ISSUE THREAD

**Issue by MattWilcox** [enupal/translate#46]
### Description

Trying to update to the latest version (2.2.0) from 2.0.0

failed to apply m210410_000000_add_message_pk

```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '24' for key 'PRIMARY'
The SQL being executed was: ALTER TABLE c3_enupaltranslate_message ADD CONSTRAINT c3_pk_mdsinpfhckkvwjmmdxkkzywjhjrrjlvlugkh PRIMARY KEY (id)

Migration: enupal\translate\migrations\m210410_000000_add_message_pk

Output:

> add primary key c3_pk_mdsinpfhckkvwjmmdxkkzywjhjrrjlvlugkh on {{%enupaltranslate_message}} (id) ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '24' for key 'PRIMARY'
The SQL being executed was: ALTER TABLE c3_enupaltranslate_message ADD CONSTRAINT c3_pk_mdsinpfhckkvwjmmdxkkzywjhjrrjlvlugkh PRIMARY KEY (id) (/app/craft/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /app/craft/vendor/yiisoft/yii2/db/Command.php(1304): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE c3...')
#1 /app/craft/vendor/yiisoft/yii2/db/Command.php(1099): yii\db\Command->internalExecute('ALTER TABLE c3...')
#2 /app/craft/vendor/yiisoft/yii2/db/Migration.php(437): yii\db\Command->execute()
#3 /app/craft/vendor/craftcms/cms/src/db/Migration.php(363): yii\db\Migration->addPrimaryKey('c3_pk_mdsinpfhc...', '{{%enupaltransl...', 'id')
#4 /app/craft/vendor/enupal/translate/src/migrations/m210410_000000_add_message_pk.php(20): craft\db\Migration->addPrimaryKey('c3_pk_mdsinpfhc...', '{{%enupaltransl...', 'id')
#5 /app/craft/vendor/craftcms/cms/src/db/Migration.php(52): enupal\translate\migrations\m210410_000000_add_message_pk->safeUp()
#6 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#7 /app/craft/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(enupal\translate\migrations\m210410_000000_add_message_pk))
#8 /app/craft/vendor/craftcms/cms/src/services/Updates.php(257): craft\db\MigrationManager->up()
#9 /app/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#10 /app/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /app/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /app/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#14 /app/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('migrate', Array)
#15 /app/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('migrate', Array)
#16 /app/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('updater/migrate', Array)
#17 /app/craft/vendor/craftcms/cms/src/web/Application.php(665): craft\web\Application->runAction('updater/migrate')
#18 /app/craft/vendor/craftcms/cms/src/web/Application.php(232): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /app/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /app/public/index.php(21): yii\base\Application->run()
#21 {main}
```

### Steps to reproduce

1. composer update

### Additional info

- Craft version: 3.6.11.1
- Database driver & version: MySQL 5.7.33
- Plugin version: 2.0.0

**Comment by andrelopez** [comment]
@MattWilcox Sorry about this issue, please update to v2.2.1 and please let us know how it goes.
