### ISSUE TITLE
Variable "elementInstance" does not exist.

### ISSUE THREAD

**Issue by svondervoort** [enupal/translate#74]
### Description
In the CP when going to the plugin for the translations an error pops up:
```
File: /vendor/enupal/translate/src/templates/index.twig Line #64
Error: Variable "elementInstance" does not exist.


{{ parent() }}
    <div class="buttons">
        <form method="post" enctype="multipart/form-data">
            {{ csrfInput() }}
            <input type="hidden" name="action" value="enupal-translate/translate/upload">
            {{ redirectInput('enupal-translate') }}
            <input type="hidden" id="importSiteId" name="importSiteId" value="{{ elementInstance.siteId }}">
            <input type="file" accept=".csv" name="translations-upload" style="display: none" />
        </form>
        <div class="btn submit translations-upload-button" data-icon="upload" style="position: relative; overflow: hidden;" role="button">{{ "Import file"|t('enupal-translate') }}</div>
    </div>
    <div class="buttons">
        <form method="post" id="sync-db-form">
```

### Steps to reproduce

1.  Install Craft & Plugin
2. Go to Enupal Translate

### Additional info

- Craft version:  Craft Pro 5.5.7
- PHP version: 8.3.14
- Database driver & version: MariaDB 11.6.2
- Plugin version: 4.0.3

**Comment by svondervoort** [comment]
This looks like something related to the PHP versions,. In PHP 8.3 we get the error when visiting the plugin in the CP, in PHP 8.2 we don't but still saving changes gives an error toast in the bottom left corner.

**Comment by andrelopez** [comment]
This issue is solved on Enupal Translate v4.1.0 thanks for reporting @svondervoort

**Comment by svondervoort** [comment]
Thanks for looking into this, but now we get another error:
```Variable "selectedSite" does not exist.```

**Comment by andrelopez** [comment]
@svondervoort  Could you please clear craft and browser caches? What is your Craft CMS version?

**Comment by svondervoort** [comment]
I tried clearing Craft cache and Browser cache.

On the test server with PHP `8.3.15`, Craft `5.5.9` and Enupal Translate `4.1.0` and mode we get the following error in the log file:

```
2025-01-09 08:08:09 [web.ERROR] [TypeError] craft\services\Sites::getSiteById(): Argument #1 ($siteId) must be of type int, string given, called in /projects/krtwebsit_ab/releases/20250108150811/vendor/enupal/translate/src/controllers/TranslateController.php on line 220 {"trace":["#0 /projects/krtwebsit_ab/releases/20250108150811/vendor/enupal/translate/src/controllers/TranslateController.php(220): craft\\services\\Sites->getSiteById()","#1 [internal function]: enupal\\translate\\controllers\\TranslateController->actionSave()","#2 /projects/krtwebsit_ab/releases/20250108150811/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#3 /projects/krtwebsit_ab/releases/20250108150811/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#4 /projects/krtwebsit_ab/releases/20250108150811/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()","#5 /projects/krtwebsit_ab/releases/20250108150811/vendor/craftcms/cms/src/web/Application.php(350): yii\\base\\Module->runAction()","#6 /projects/krtwebsit_ab/releases/20250108150811/vendor/craftcms/cms/src/web/Application.php(649): craft\\web\\Application->runAction()","#7 /projects/krtwebsit_ab/releases/20250108150811/vendor/craftcms/cms/src/web/Application.php(312): craft\\web\\Application->_processActionRequest()","#8 /projects/krtwebsit_ab/releases/20250108150811/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()","#9 /projects/krtwebsit_ab/releases/20250108150811/web/index.php(12): yii\\base\\Application->run()","#10 {main}"],"memory":7712056,"exception":"[object] (TypeError(code: 0): craft\\services\\Sites::getSiteById(): Argument #1 ($siteId) must be of type int, string given, called in /projects/krtwebsit_ab/releases/20250108150811/vendor/enupal/translate/src/controllers/TranslateController.php on line 220 at /projects/krtwebsit_ab/releases/20250108150811/vendor/craftcms/cms/src/services/Sites.php:650)"}
```

Locally with PHP `8.3.14`, Craft `5.5.9` and Enupal `4.1.0` and mode we get the previously mentioned error when visiting the Enupal Translate plugin page.

**Comment by svondervoort** [comment]
Just to be sure I also tried it locally on a different Craft site, which does have multiple sites, there we don't have any issue.

The Craft site where we do have the issue only has one site, but still we use the plugin to translate keys throughout the site. When adding another site the error is gone.

So maybe its an issue with single site configs?

**Comment by andrelopez** [comment]
@svondervoort thanks the info! I am debugging the issue with the one site scenario

**Comment by andrelopez** [comment]
Hi @svondervoort the issue should be solved on v4.1.1 please let me know if that works

**Comment by svondervoort** [comment]
Hi, thanks. I just tested and it is working correctly.

**Comment by StanSteen** [comment]
Hi, 

The same issue occurs on a craft 4.14.9 project: 

Variable "elementInstance" does not exist.

vendor/enupal/translate/src/templates/index.twig

    {{ parent() }}
    <div class="buttons">
        <form method="post" enctype="multipart/form-data">
            {{ csrfInput() }}
            <input type="hidden" name="action" value="enupal-translate/translate/upload">
            {{ redirectInput('enupal-translate') }}
            <input type="hidden" id="importSiteId" name="importSiteId" value="{{ elementInstance.siteId }}">
            <input type="file" accept=".csv" name="translations-upload" style="display: none" />
        </form>
        <div class="btn submit translations-upload-button" data-icon="upload" style="position: relative; overflow: hidden;" role="button">{{ "Import file"|t('enupal-translate') }}</div>
    </div>
    <div class="buttons">
        <form method="post" id="sync-db-form">


PHP version : 8.2.27
Craft : Craft Pro 4.14.9
Plugin version : 3.1.0
Database driver & version: MariaDB 11.6.2

**Comment by S-n-d** [comment]
Having the exact same issue as Patchyy.

PHP version : 8.1.31
Craft : Craft Pro 4.13.10
Plugin version : 3.1.0
Database driver & version: MySQL 8.0

**Comment by junioradwise** [comment]
I get the same error after installing in fresh local install.

PHP version: 8.3.17
Craft version: 4.14.10
Plugin version: 3.1.0

**Comment by andrelopez** [comment]
Thanks for reporting the issue on Craft CMS v4, we just released Enupal Translate v3.2.0 with a fix to this issue.
